function [] = make_distortion_fig(src_path,target_path,colormap)
repeats_init();
axis_options = {'enlargelimits=false'};  
sensitivity = load(src_path);
is_legend_on = 'On';

data = innerjoin(sensitivity.res,sensitivity.gt, ...
                 'LeftKeys','ex_num','RightKeys','ex_num');
q_gt = unique(data.q_gt)*sum(2*sum(sensitivity.cam.cc))^2;
assert(numel(q_gt)>0,'Cannot have different distortion parameters');
qres = array2table([data.q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    data.ransac_q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    1-data.q./data.q_gt ...
                    1-data.ransac_q./data.q_gt ...
                    data.rewarp ...
                    data.ransac_rewarp ], ...
                   'VariableNames', ...
                   {'q','ransac_q', 'q_relerr', ...
                    'ransac_q_relerr', 'rewarp','ransac_rewarp'}); 

res = [data(:,{'ex_num','scene_num','solver','sigma'}) qres];
solver_list = unique(res.solver);
boxplot_colors = make_boxplot_colors(data,colormap);

make_grouped_boxplot(data, {'ransac_rewarp'}, ...
                     { 'q_gt', 'solver' }, ...
                     'xlabel', ...
                     'Normalized Divsion Model Parameter $\lambda$', ...
                     'ylabel', ...
                     ['$\Delta^{\mathrm{warp}}_{\' ...
                    'mathrm{RMS}}$ [pixels]'], ...
                     'ylim', [0 20], ...
                     'xticklabels', num2str(q_gt), ...
                     'yticks',[0:5:20], ...
                     'location','northwest', ...
                     'colors', boxplot_colors, ...
                     'legend',is_legend_on);

drawnow;
cleanfigure;
matlab2tikz([target_path 'ransac_distortion.tikz'], ...
             'width', '\fwidth','extraAxisOptions',axis_options);


function boxplot_colors = make_boxplot_colors(res,colormap)
num_solvers = numel(unique(res.solver));
solver_order = cellstr(res(1:num_solvers,:).solver);
boxplot_colors = zeros(num_solvers,3);
for k = 1:num_solvers
    boxplot_colors(k,:) = colormap(solver_order{k});
end