function v = apply_rigid_xforms(u,theta,t)
c = cos(theta);
s = sin(theta);
t = repmat([t;zeros(1,size(t,2))],3,1);

Ru = ones(size(u));
Ru([1 2 4 5 7 8],:) = ...
    [ c.*u(1,:)-s.*u(2,:); ...
      s.*u(1,:)+c.*u(2,:); ...
      c.*u(4,:)-s.*u(5,:); ...
      s.*u(4,:)+c.*u(5,:); ...
      c.*u(7,:)-s.*u(8,:); ...
      s.*u(7,:)+c.*u(8,:) ];
v = Ru+t; 