%
%  Copyright (c) 2018 James Pritts
%  Licensed under the MIT License (see LICENSE for details)
%
%  Written by James Pritts
%
function cam = make_ccd(f_mm,ccd_mm,nx,ny)
f = nx*f_mm/ccd_mm;
cc = [nx/2+0.5; ...
      ny/2+0.5];
K = [2*f 0 cc(1);
     0 f cc(2);
     0 0 1];

fov = 2*atan2(ccd_mm/2,f_mm);

cam = struct('K', K, ...
             'f', f, ...
             'cc',cc, ...
             'hfov', fov, ...
             'ccd_mm', ccd_mm, ...
             'f_mm', f_mm, ...
             'nx',nx, ...
             'ny',ny);
