function [] =  cvdb_clear(conn)
    connh = conn.Handle;
    warning('db_clear just erased all the cvtoolkit tables in your database');
    stm = connh.prepareStatement(['DROP TABLE IF EXISTS imgs, img_pairs, ' ...
                        'stereo_sets, rnsc, rnsc_cfgs, ' ...
                        'stereo_experiments, ' ...
                        'img_sets, tags, stereo_taggings, primitives, ' ...
                        'geometry_taggings, calib_data, calib_results, ' ...
                        'rnsc_taggings, detector_cfgs, detectors, descriptor_cfgs, ' ...
                        'descriptors,  tc_cfgs,  tc, two_view_matrices, ' ...
                        'gs, gs_cfgs, rnsc_primitives, rnsc_trials']);
    stm.execute();