function [] =  cvdb_clear(conn)
    connh = conn.Handle;
    warning('db_clear just erased all the cvtoolkit tables in your database');
    stm = connh.prepareStatement(['DROP TABLE IF EXISTS imgs, img_pairs, ' ...
                        'stereo_sets, rnsc, rnsc_cfgs, ' ...
                        'stereo_experiments, tc, ' ...
                        'img_sets, tags, stereo_taggings, primitives, ' ...
                        'geometry_taggings, calib_data, calib_results, ' ...
                        'rnsc_taggings']);    
    stm.execute();