global conn CASS_CFG

conn = cvdb_open('nash.felk.cvut.cz', ...
                 'ransac', ...
                 'prittjam', ...
                 'gauss123');

CASS_CFG.db_root = '/mnt/fry';
CASS_CFG.imagedb_cluster = 'cmpgrid_cassandra';