function [] = cvdb_create(conn)
    connh = conn.Handle;    
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''imgs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE imgs(' ...
                            'id BINARY(32), ' ...
                            'url TEXT, ' ...
                            'relative_path TEXT NOT NULL, ' ...
                            'name TEXT NOT NULL, ' ...
                            'ext TEXT NOT NULL, ' ...
                            'height INTEGER NOT NULL, ' ...
                            'width INTEGER NOT NULL, ' ...
                            'PRIMARY KEY(id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''img_pairs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE img_pairs(' ...
                            'id BINARY(32) NOT NULL, ' ...
                            'img1_id BINARY(32) NOT NULL, ' ...
                            'img2_id BINARY(32) NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(img1_id) REFERENCES imgs(id), ' ...
                            'CONSTRAINT FOREIGN KEY(img2_id) REFERENCES imgs(id))']);
        stm.execute();
    end    
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''stereo_sets''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE stereo_sets(' ...
                            'id INTEGER AUTO_INCREMENT, ', ...
                            'name VARCHAR(256) NOT NULL, ' ...
                            'pair_id BINARY(32) NOT NULL, ' ...
                            'description TEXT, ' ...
                            'acknowledgement TEXT, ' ...
                            'refs TEXT, ' ...
                            'PRIMARY KEY(id), ' ...
                            'INDEX(name), ' ...
                            'CONSTRAINT FOREIGN KEY(pair_id) ' ...
                            'REFERENCES img_pairs(id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''img_sets''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE img_sets(' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'name VARCHAR(128) NOT NULL, ' ...
                            'img_id BINARY(32) NOT NULL, ' ...
                            'description TEXT, ' ...
                            'PRIMARY KEY(id), ' ...
                            'INDEX(name), ' ...
                            'CONSTRAINT FOREIGN KEY(img_id) REFERENCES imgs(id))']);
        stm.execute();
    end

    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''stereo_experiments''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        sql_statement = ['CREATE TABLE stereo_experiments (' ...
                         'id BINARY(16), ' ...
                         'title VARCHAR(128) NOT NULL, ' ...
                         'begin_time TIMESTAMP DEFAULT ''0000-00-00 00:00:00'', ' ...
                         'end_time TIMESTAMP DEFAULT ''0000-00-00 00:00:00'', ' ...
                         'user VARCHAR(256), ' ...
                         'pair_id BINARY(32) NOT NULL, ' ...
                         'tc_cfg_id BINARY(16) NOT NULL, ' ...
                         'rnsc_cfg_id BINARY(16) NOT NULL, ' ...
                         'us_elapsed_time INTEGER, ' ... 
                         'description TEXT, ' ...
                         'PRIMARY KEY(id), ' ...
                         'CONSTRAINT FOREIGN KEY(pair_id) REFERENCES ' ...
                         'img_pairs(id))'];

        stm = connh.prepareStatement(sql_statement);
        stm.execute();
        
%        sql_statement2 = [ 'delimiter | CREATE TRIGGER begin_stereo_experiment BEFORE INSERT ' ...
%                           'ON stereo_experiments ' ...
%                           'FOR EACH ROW SET NEW.begin = NOW() | ' ...
%                           'delimiter ;']; 
%
%                          'CREATE TRIGGER ' ...
%                          'end_stereo_experiment ' ...
%                          'BEFORE UPDATE ON stereo_experiments ' ...
%                          'FOR EACH ROW SET NEW.end = NOW()' ...
%                          'CREATE TRIGGER ' ...
%                          'register_user ' ...
%                          'BEFORE INSERT ON stereo_experiments ' ...
%                          'FOR EACH ROW SET NEW.user = SESSION_USER() '];
%                          stm = connh.prepareStatement(sql_statement2);
%                          stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''rnsc_cfgs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE rnsc_cfgs (' ...
                            'id BINARY(16) NOT NULL, ' ...
                            'sample_size INTEGER, ' ...
                            'threshold REAL, ' ...
                            'confidence REAL, ' ...
                            'min_trials INTEGER, ' ...
                            'max_trials INTEGER, ' ...
                            'max_data_retries INTEGER, ' ...
                            'model_fn TEXT, ' ...
                            'error_fn TEXT, ' ...
                            'score_fn TEXT, ' ...
                            'sample_degen_fn TEXT, ' ...
                            'model_degen_fn TEXT, ' ...
                            'lo_fn TEXT, ' ...
                            'always_model_degen BOOLEAN, ' ...
                            'PRIMARY KEY(id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''rnsc''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE rnsc (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'title VARCHAR(128) NOT NULL, ' ...
                            'cfg_id BINARY(16) NOT NULL, ' ...
                            'inlying_set BLOB NOT NULL, ' ...
                            'errors BLOB, ' ...
                            'score DOUBLE, ' ...
                            'samples_drawn INTEGER NOT NULL, ' ...
                            'sample_degen_count INTEGER, ' ...
                            'us_time_elapsed INTEGER, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(cfg_id) REFERENCES ' ...
                            'rnsc_cfgs(id))']);
        stm.execute();
    end
    

    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''gs_cfgs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE gs_cfgs (' ...
                            'id BINARY(16) NOT NULL, ' ...
                            'max_iter INTEGER, ' ...
                            'epsilon DOUBLE, ' ...
                            'model_fn TEXT, ' ...
                            'error_fn TEXT, ' ...
                            'score_fn TEXT, ' ...
                            'PRIMARY KEY(id))']);
        stm.execute();
    end    
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''gs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE gs (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'title VARCHAR(128) NOT NULL, ' ...
                            'cfg_id BINARY(16), ' ...
                            'weights BLOB NOT NULL, ' ...
                            'errors BLOB, ' ...
                            'score DOUBLE, ' ...
                            'iterations INTEGER NOT NULL, ' ...
                            'us_time_elapsed INTEGER, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(gd_cfg_id) REFERENCES ' ...
                            '(id))']);
        stm.execute();
    end    
    
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''primitives''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE primitives (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'data BLOB NOT NULL, ' ...
                            'img_id BINARY(32) NOT NULL, ' ...
                            'name VARCHAR(256), ' ...
                            'PRIMARY KEY(id), ' ...
                            'INDEX(name), ' ...
                            'CONSTRAINT FOREIGN KEY(img_id) REFERENCES ' ...
                            'imgs(id))']);
        stm.execute();
    end     
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''rnsc_primitives''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE rnsc_primitives (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'rnsc_id INTEGER NOT NULL, ' ....
                            'primitives_id INTEGER NOT NULL, ' ...
                            'sample_set BLOB NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(rnsc_id) REFERENCES ' ...
                            'rnsc(id), ' ...
                            'CONSTRAINT FOREIGN KEY(primitives_id) ' ...
                            'REFERENCES primitives(id))']);

        stm.execute();
    end        
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''tags''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE tags (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'name VARCHAR(128) NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'INDEX(name))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''stereo_taggings''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE stereo_taggings (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'tag_id INTEGER NOT NULL, ' ....
                            'pair_id BINARY(32) NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(tag_id) REFERENCES ' ...
                            'tags(id), ' ...
                            'CONSTRAINT FOREIGN KEY(pair_id) ' ...
                            'REFERENCES img_pairs(id))']);
        stm.execute();
    end

    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''geometry_taggings''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE geometry_taggings (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'tag_id INTEGER NOT NULL, ' ...
                            'primitives_id INTEGER NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(tag_id) REFERENCES ' ...
                            'tags(id), ' ...
                            'CONSTRAINT FOREIGN KEY(primitives_id) REFERENCES ' ...
                            'primitives(id))']);
        stm.execute();
    end
    
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''rnsc_taggings''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE rnsc_taggings (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'tag_id INTEGER NOT NULL, ' ...
                            'rnsc_id INTEGER NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(tag_id) REFERENCES ' ...
                            'tags(id), ' ...
                            'CONSTRAINT FOREIGN KEY(rnsc_id) REFERENCES ' ...
                            'rnsc(id))']);
        stm.execute();
    end
    
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''calib_results''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE calib_results (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'results BLOB, ' ...
                            'calib_data_name VARCHAR(256) NOT NULL, ' ...
                            'name TEXT NOT NULL, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(calib_data_name) REFERENCES ' ...
                            'calib_data(name))']);
        stm.execute();
    end

    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''detector_cfgs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE detector_cfgs (' ...
                            'id BINARY(16) NOT NULL, ' ...
                            'cfg BLOB, ' ...
                            'PRIMARY KEY(id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''detectors''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE detectors (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'cfg_id BINARY(16) NOT NULL, ' ...
                            'pair_id BINARY(32) NOT NULL, ' ...
                            'data BLOB, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(cfg_id) REFERENCES ' ...
                            'detector_cfgs(cfg_id),y ' ...
                            'CONSTRAINT FOREIGN KEY(pair_id) REFERENCES ' ...
                            'img_pairs(pair_id))']);
        stm.execute();
    end

    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''descriptor_cfgs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE descriptor_cfgs (' ...
                            'id BINARY(16) NOT NULL, ' ...
                            'cfg BLOB, ' ...
                            'PRIMARY KEY(id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''descriptors''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE descriptors (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'cfg_id BINARY(16) NOT NULL, ' ...
                            'pair_id BINARY(32) NOT NULL, ' ...
                            'data BLOB, ' ...
                            'PRIMARY KEY(id), ' ... 
                            'CONSTRAINT FOREIGN KEY(cfg_id) REFERENCES ' ...
                            'descriptor_cfgs(cfg_id), ' ...
                            'CONSTRAINT FOREIGN KEY(pair_id) REFERENCES ' ...
                            'img_pairs(pair_id))']);
        stm.execute();
    end

    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''tc_cfgs''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE tc_cfgs (' ...
                            'id BINARY(16) NOT NULL, ' ...
                            'cfg BLOB, ' ...
                            'PRIMARY KEY(id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''tc''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE tc (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'cfg_id BINARY(16) NOT NULL, ' ...
                            'pair_id BINARY(32) NOT NULL, ' ...
                            'data BLOB NOT NULL, ' ...
                            'count INTEGER NOT NULL, ' ...
                            'type ENUM(''LAF''), ' ...
                            'us_time_elapsed INTEGER, ' ...
                            'PRIMARY KEY(id), '  ...
                            'CONSTRAINT FOREIGN KEY(cfg_id) REFERENCES ' ...
                            'tc_cfgs(cfg_id), ' ...
                            'CONSTRAINT FOREIGN KEY(pair_id) REFERENCES ' ...
                            'img_pairs(pair_id))']);
        stm.execute();
    end
    
    stm = connh.prepareStatement(['SELECT COUNT(*) FROM information_schema.tables ' ...
                        'WHERE table_name=''two_view_matrices''']);
    rs = stm.executeQuery();
    rs.next();
    count = rs.getInt(1);
    if (count == 0)
        stm = connh.prepareStatement(['CREATE TABLE two_view_matrices (' ...
                            'id INTEGER AUTO_INCREMENT, ' ...
                            'matrix BINARY(72) NOT NULL, ' ...
                            'type ENUM(''fundamental'',''affine fundamental'',''essential'',''homography'',''affinity''), ' ...
                            'pair_id BINARY(32) NOT NULL, ' ...
                            'rnsc_id INTEGER, ' ...
                            'gs_id INTEGER, ' ...
                            'PRIMARY KEY(id), ' ...
                            'CONSTRAINT FOREIGN KEY(rnsc_id) ' ...
                            'REFERENCES rnsc(id), ' ...
                            'CONSTRAINT FOREIGN KEY(gs_id) ' ...
                            'REFERENCES gs(id))']);
        stm.execute();
    end