function Rt = fit_motion_centroids(Gm,xform_list)
Gm = reshape(Gm,1,[]);
Rt0 = [xform_list(:).Rt];
%Rt0(1,:) = msplitapply(@(theta) unwrap(theta), Rt0(1,:), Gm);
%Rt = cmp_splitapply(@(u) ...
%                    [ atan2(mean(sin(u(1,:))), mean(cos(u(1,:)))); ...
%                    mean(u(2:3,:),2); ...
%                    u(4,1) ], ...
%                    Rt0,Gm);
%
Rt = cmp_splitapply(@(u) fit_motion_impl(u),Rt0,Gm);

function v = fit_motion_impl(u)
v = [atan2(mean(sin(u(1,:))), mean(cos(u(1,:)))); ...
     mean(u(2:3,:),2); ...
     u(4,1)];

%v = [atan2(mean(sin(u(1,1))), mean(cos(u(1,1)))); ...
% mean(u(2:3,1),2); ...
% u(4,1)];
%
assert(all(u(4,:) == u(4,1)),'reflections are mixed');
