function res = rectify_planes(x,Gsamp,Gapp,solver,cc)
solver = WRAP.lafmn_to_qAl(solver);
[model_list,lo_res_list,stats_list] = ...
    fit_coplanar_patterns(solver,x, ...
                          Gsamp,Gsamp,cc,1);
res = struct('model_list', model_list, ...
             'lo_res_list', lo_res_list, ...
             'stats_list', stats_list);