function [] = distortion
dt = datestr(now,'yyyymmdd_HHMMSS');

if ~exist('results', 'dir')
    mkdir('results');
end

nx = 1000;
ny = 1000;
cc = [nx/2+0.5; ...
      ny/2+0.5];

[solver_names,solver_list,colormap] = IJCV19.make_solver_list();

[res,gt,cam] = TEST.sensitivity(solver_names([5:6 9]), ...
                                solver_list([5:6 9]), ...
                                solver_names, ...
                                'nx',nx,'ny',ny, ...
                                'cc',cc, 'CcdSigmaList', 1, ...
                                'normqlist',[-5:1:0], ...
                                'RigidXform','Rt');

keyboard;
save(strcat('results/distortion_', dt, '.mat'), ...
     'res','gt','cam');