function [] = make_sensitivity_figs()
color_list = [  ...
    0.5 0 0.5; ...
    1 69/255 0; ...
    0 0 0; ...
    0 0 1; ...
    0 1 0; ...
    1 0 0; ...
    1 0 1; ...
    1 1 0];

colormap = containers.Map({'$\mH22\vl s$', ...
                    '$\mH22\lambda$', ...
                    '$\mH22\vl$', ...
                    '$\mH222\vl\lambda s_i$', ...
                    '$\mH32\vl\lambda s_i$', ...
                    '$\mH^{\prime}222\vl\lambda s_i$'}, ...
                          [1 2 3 4 5 7]);

src_path = 'rt_sensitivity_20190303.mat';
target_path = '/home/jbpritts/Documents/ijcv19/fig2/';
TEST.make_sensitivity_figs(src_path,target_path,colormap,color_list);