function [solver_names,solver_list,colormap] = make_stabilty_solver_list()
solver_names = {'$\mH222\vl\lambda$', ...
                '$\mH32\vl\lambda$', ...
                '$\mH4\vl\lambda$', ...
                '$\mH222\vl\lambda$ (grevlex)', ...   
                '$\mH32\vl\lambda$ (grevlex)', ...
                '$\mH4\vl\lambda$ (grevlex)', ...
                '$\mH^{\prime}222\vl\lambda$', ...
                '$\mH^{\prime}32\vl\lambda$', ...
                '$\mH^{\prime}4\vl\lambda$', ...
                '$\mH^{\prime}222\vl\lambda$ (grevlex)', ...
                '$\mH^{\prime}32\vl\lambda$ (grevlex)', ...
                '$\mH^{\prime}4\vl\lambda$ (grevlex)' }; 

solver_list = [ ...
    WRAP.laf222_to_ql() ...
    WRAP.laf32_to_ql() ...
    WRAP.laf4_to_ql() ...
    WRAP.laf222_to_ql('solver','accv18_grevlex') ...
    WRAP.laf32_to_ql('solver','accv18_grevlex') ...
    WRAP.laf4_to_ql('solver','accv18_grevlex') ...
    WRAP.laf222_to_ql('solver', 'ijcv19') ...
    WRAP.laf32_to_ql('solver', 'ijcv19') ...
    WRAP.laf4_to_ql('solver', 'ijcv19') ...
    WRAP.laf222_to_ql('solver', 'ijcv19_grevlex') ...
    WRAP.laf32_to_ql('solver', 'ijcv19_grevlex') ...
    WRAP.laf4_to_ql('solver', 'ijcv19_grevlex') ] ; 

color_list = [0 0 255; ...
              0 255 0; ...
              255 0 0; ...
              0 0 255; ...    
              0 255 0; ...
              255 0 0; ...
              0 255 255; ...
              255 0 255; ...
              245 245 0; ...
              0 255 255; ...
              255 0 255; ...
              245 245 0 ] / 255;
    
tst = mat2cell(color_list,ones(12,1),3);
colormap = containers.Map(solver_names, tst);