function [] = rt_sensitivity()
nx = 1000;
ny = 1000;
cc = [nx/2+0.5; ...
      ny/2+0.5];

%name_list = {'$\mH22\vl s$', ...
%             '$\mH22\lambda$', ...
%             '$\mH22\vl$', ...
%             '$\mH222\vl\lambda s_i$', ...
%             '$\mH32\vl\lambda s_i$', ...
%             '$\mH4\vl\lambda s_i$'}; 
%
%solver_list = [ ...
%    WRAP.laf22_to_l('solver_type','linear'), ...        
%    WRAP.laf22_to_qH() ...
%    WRAP.laf22_to_l('solver_type','polynomial'), ... 
%    WRAP.laf222_to_ql(), ...
%    WRAP.laf32_to_ql(), ...
%    WRAP.laf4_to_ql()] ;

solver_list = [  WRAP.laf22_to_l('solver_type','linear'), ...        
                 WRAP.laf22_to_qH() ...
                 WRAP.laf22_to_l('solver_type','polynomial'), ... 
                 WRAP.laf222_to_ql(), ...
                 WRAP.laf32_to_ql(), ...
                 WRAP.laf222_to_ql({'solver', 'ijcv19'}) ];
 
all_solver_names = {'$\mH22\vl s$', ...
                    '$\mH22\lambda$', ...
                    '$\mH22\vl$', ...
                    '$\mH222\vl\lambda s_i$', ...
                    '$\mH32\vl\lambda s_i$', ...
                    '$\mH^{\prime}222\vl\lambda s_i$'}; 


name_list = all_solver_names; 

dstr = datestr(now,'yyyymmdd');
out_name = ['rt_sensitivity_' dstr '.mat'];

TEST.sensitivity(out_name,name_list,solver_list, all_solver_names, ...
                 'nx',nx,'ny',ny,'cc',cc);