function [] = cvdb_ins_canonical_stereo_sets(conn)
% construct file paths
    connh = conn.Handle;
    base_path = '/home.stud/prittjam/cvtoolkit/';
    image_set_path = [base_path 'corridor/'];
    corridor_image_set =  ...
        { ...
            {'bt.000.pgm','bt.010.pgm'}, ...
            {'bt.002.pgm','bt.009.pgm'}, ...
            {'bt.004.pgm','bt.007.pgm'} ...
        };
    cvdb_ins_stereo_set(conn, 'Corridor', image_set_path, corridor_image_set);
    
    image_set_path = [base_path 'wbstestnew/'];
    wbstestnew_image_set = ...
        { ...
            {'wallA.jpg','wallB.jpg'}, ...
            {'bookshA.png', 'bookshB.png'}, ...
            {'castleA.png','castleB.png'}, ...
            {'plantA.png','plantB.png'}, ...
            {'kampaA.png','kampaB.png'}, ...
            {'rotundaA.png','rotundaB.png'}, ...
            {'shout1.png','shout3.png'}, ...
            {'washA.png','washB.png'}, ...
            {'zoomA.png','zoomB.png'}, ...
            {'graffA.png','graffB.png'}
        };
    cvdb_ins_stereo_set(conn, 'WbsNew', image_set_path, wbstestnew_image_set);
    
    image_set_path = [base_path 'oxford_pics/'];
    arandjelovic_image_set = ...
        { ...
            {'raglan/lawn_0~1.tif', 'raglan/lawn_0~4.tif'}, ...
            {'raglan/lawn_0~1.tif', 'raglan/lawn_0~2.tif'}, ...
            {'raglan/lawn_0~1.tif', 'raglan/lawn_0~3.tif'}, ...
            {'raglan/floor_~3.tif', 'raglan/roof_0~2.tif'}, ...
            {'raglan/fle25c~1.tif', 'raglan/floor_~1.tif'}, ...
            {'model_house/house.000.pgm', 'model_house/house.003.pgm'}, ...
            {'im1.png','im2.png'}, ...
            {'img1.jpg', 'img2.jpg'}, ...
            {'shed1.jpg', 'shed2.jpg'}, ...
            {'valbonne/002.tif', 'valbonne/011.tif'}, ...
            {'valbonne/003.tif', 'valbonne/004.tif'}, ...
            {'wadham/003.jpg', 'wadham/005.jpg'}, ...
            {'washA.png', 'washB.png'}, ...
            {'wallA.jpg', 'wallB.jpg'} ...
        };

    cvdb_ins_stereo_set(conn, 'Arandjelovic', image_set_path, arandjelovic_image_set);
end