function [] = pami_ct_sensitivity()
nx = 1000;
ny = 1000;
cc = [nx/2+0.5; ...
      ny/2+0.5];

name_list = { '$\mH2\vl\lambda$', ...
              '$\mH2\vl\vu s_{\vu}\lambda$'};

solver_list = [ ...
    WRAP.laf2_to_qlsu() ...
    WRAP.laf2_to_ql() ...
              ];

dstr = datestr(now,'yyyymmdd');
out_name = ['ct_sensitivity_' dstr '.mat'];

TEST.sensitivity(out_name,name_list,solver_list, ...
                 'nx',nx,'ny',ny,'cc',cc, ...
                 'RigidXform','t', ...
                 'CcdSigmaList',0, ...
                 'NormQList',-4);