function A = laf_make_A_from_3p(geom)
n = size(geom,2);
A = squeeze(reshape([geom(1:3,:)-geom(4:6,:); ...
                    geom(7:9,:)-geom(4:6,:); ...
                    geom(4:6,:)], ...
                    3,3,[]));
if ndims(A) > 2
    A = num2cell(A,[1 2]);
end