function draw2d_piecewise_linear_lafs(ax1,x,y,cmap)
k = size(x,1)/2;

tmp = [];
if nargin > 3
    tmp = get(ax1,'ColorOrder');
    set(ax1,'ColorOrder', cmap);
end

hold all;
h1 = plot(x,y);
scatter(x(k+1:2*k:end), ...
        y(k+1:2*k:end), ...
        10,'k','filled');
scatter(x(2*k+1:2*k:end), ...
        y(2*k+1:2*k:end), ...
        10,'k','filled');
h2 = scatter(x(1:2*k:end), ...
             y(1:2*k:end));
hold off;

set(h1,           ...
    'LineWidth'       , 2);

set(get(h2,'Children'),           ...
    'LineWidth'       , 1           , ...
    'Marker'          , 'o'         , ...
    'MarkerSize'      , 4           , ...
    'MarkerEdgeColor' , [.2 .2 .2]  , ...
    'MarkerFaceColor' , [.7 .7 .7]  );

if nargin > 3
    set(ax1,'ColorOrder', tmp);
end