function draw2d_repeated_lafs(ax1,u,vis)
iv = nonzeros(vis');
[ii,jj] = find(vis');
color_set = repmat(varycolor(size(vis,2)),size(vis,1),1);
idx = sub2ind(size(vis'),ii,jj);

tmp = get(ax1,'ColorOrder');
set(ax1,'ColorOrder',color_set(idx,:));

x = reshape(u(1:3:end,iv),3,[]);
y = reshape(u(2:3:end,iv),3,[]);

hold all;
h1 = plot(x,y);
h2 = scatter(x(:),y(:),10);
h3 = scatter(x(1:3:end), ...
             y(1:3:end));
hold off;

set(h1, ...
    'LineWidth'       , 2, ...
    'MarkerEdgeColor' , [.2 .2 .2]);

set(get(h2,'Children'),           ...
    'LineWidth'       , 1           , ...
    'Marker'          , 'o'         , ...
    'MarkerSize'      , 2.5           , ...
    'MarkerEdgeColor' , [.2 .2 .2]  , ...
    'MarkerFaceColor' , [.7 .7 .7]  );

set(get(h3,'Children'),           ...
    'LineWidth'       , 1           , ...
    'Marker'          , 'o'         , ...
    'MarkerSize'      , 4           , ...
    'MarkerEdgeColor' , [.2 .2 .2]  , ...
    'MarkerFaceColor' , [.7 .7 .7]  );

set(ax1,'ColorOrder', tmp);
