function cost = calc_cost(x,xp,cspond,Gm,q,cc,H,Rtij)
Hinv = inv(H);
invRtij = multinv(Rtij);
ut_j =  PT.rd_div(PT.renormI(PT.mtimesx(multiprod(Hinv,Rtij(:,:,Gm)), ...
                                        xp(:,cspond(1,:)))),cc,q);
ut_i =  PT.rd_div(PT.renormI(PT.mtimesx(multiprod(Hinv,invRtij(:,:,Gm)), ...
                                        xp(:,cspond(2,:)))),cc,q);
cost = [ut_j-x(:,cspond(2,:)); ...
        ut_i-x(:,cspond(1,:))];