function T =  cam_make_ld_div_tform(cc,q)
tdata.cc = cc;
tdata.qd = q;
tdata.qu = q;
T = maketform('custom', 2, 2, ...
              @cam_undistort_div_tform, ...
              @cam_distort_div_tform, ...
              tdata);