function [] =  cam_make_dist_tform(cc,q)
tdata.cc = cc;
tdata.qd = q;
tdata.qu = q;
T = maketform('custom', 2, 2, ...
              @cam_udist_div_tformfwd, ...
              @cam_dist_div_tforminv, ...
              tdata);