function timg = ru_div(img,cc,q,varargin)
nx = size(img,2);
ny = size(img,1);
border = [0.5    0.5; ...
          nx+0.5 0.5; ...
          nx+0.5 ny+0.5; ...
          0.5    ny+0.5];

T = CAM.make_rd_div_tform(cc,q);

tborder = tformfwd(T,border);

timg = imtransform(img,T,'bicubic', ...
                   'XData',[tborder(1,1) tborder(2,1)], ...
                   'YData',[tborder(1,2) tborder(3,2)], ...
                   varargin{:});
