function timg = img_undistort_div(img,cc,q)
nx = size(img,2);
ny = size(img,1);
border = [0.5    0.5; ...
          nx+0.5 0.5; ...
          nx+0.5 ny+0.5; ...
          0.5    ny+0.5];
tdata.cc = cc;
tdata.q = q;
L = maketform('custom',2,2, ...
              @cam_undistort_div_tform, ...
              @cam_distort_div_tform, ...
              struct('cc',cc,'q',q));

tborder = tformfwd(L,border);

timg = imtransform(img,L,'bicubic', ...
                   'Fill', [255;255;255], ...
                   'XData',[tborder(1,1) tborder(2,1)], ...
                   'YData',[tborder(1,2) tborder(3,2)]);