function [] = make_sensitivity_figs()
greedy_repeats_init('..');
sensitivity = load('sensitivity.mat');
data = innerjoin(sensitivity.res,sensitivity.gt, ...
                 'LeftKeys','ex_num','RightKeys','ex_num');
q_gt = unique(data.q_gt)*sum(2*sum(sensitivity.cam.cc))^2;

assert(numel(q_gt)>0,'Cannot have different distortion parameters');
qres = array2table([data.q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    data.ransac_q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    1-data.q./data.q_gt ...
                    1-data.ransac_q./data.q_gt ...
                    data.rewarp ...
                    data.ransac_rewarp ], ...
                   'VariableNames', ...
                   {'q','ransac_q', 'q_relerr', ...
                    'ransac_q_relerr', 'rewarp','ransac_rewarp'}); 

res = [data(:,{'ex_num','scene_num','solver','sigma'}) qres];
solver_list = unique(res.solver);

keyboard;

Lia = res.sigma > 0; 

Lib = ismember(res.solver, ...
               setdiff(solver_list, {'$\mH22\vl s$'}));
Lic = ismember(res.solver, ...
               setdiff(solver_list, '$\mH22\vl s$'));
Lid = ismember(res.solver,setdiff(solver_list,{'$\mH22\lambda$'}));

color_list = [ 0 1 1; ...
               1 0 1; ...
               0 0 0; ...
               1 1 0; ...
               0 0 1; ...
               0 1 0; ...
               1 0 0];

lbound = q_gt-4;
ubound = q_gt+4;

axis_options = {'enlargelimits=false'} 
lambda_colors = [1:2 4:7];

%ind = find(Lia & Lib);
%ax1 = make_grouped_boxplot(res(ind,:), ...
%                           {'q'},{ 'sigma', 'solver' }, ...
%                           'ylabel', 'Estimated distortion parameter $\hat{ \lambda }$', ...
%                           'ylim', [lbound ubound], ...
%                           'yticks',[lbound:2:ubound], ...
%                           'truth', q_gt, ...
%                           'location','northwest', ...
%                           'colors', color_list(lambda_colors,:));
%
%
%drawnow;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/lambda_sensitivity.tikz',...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%ax2 = make_grouped_boxplot(res(ind,:), ...
%                           {'ransac_q'},{ 'sigma','solver' }, ...
%                           'ylabel', 'Estimated distortion parameter $\hat{ \lambda }$', ...
%                           'ylim', [lbound ubound], ...
%                           'yticks',[lbound:2:ubound], ...
%                           'truth', q_gt, ...
%                           'location','northwest', ...
%                           'colors', color_list(lambda_colors,:));
%drawnow;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/ransac_lambda_sensitivity.tikz',...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%ax3 = make_grouped_boxplot(res(ind,:), {'q_relerr'},{ 'sigma', 'solver' }, ...
%                           'ylim', [-0.6 0.6], ...
%                           'yticks',[-0.8:0.2:0.8], ...
%                           'truth', 0.0, ...
%                           'location','northwest', ...
%                           'colors', color_list(lambda_colors,:), ...
%                            'ylabel', '$(\lambda-\hat{\lambda})/\lambda$');
%drawnow;
%cleanfigure;
%matlab2tikz(['/home/prittjam/Documents/eccv18/fig/' ...
%             'rel_lambda_sensitivity.tikz'], ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%ax4 = make_grouped_boxplot(res(ind,:), {'ransac_q_relerr'},{ 'sigma', 'solver' }, ...
%                           'ylim', [-0.6 0.6], ...
%                           'yticks',[-0.8:0.2:0.8], ...
%                           'truth', 0.0, ...
%                           'location','northwest', ...
%                           'colors', color_list(lambda_colors,:), ...
%                           'ylabel', '$(\lambda-\hat{\lambda})/\lambda$');
%drawnow;
%cleanfigure;
%matlab2tikz(['/home/prittjam/Documents/eccv18/fig/' ...
%             'ransac_rel_lambda_sensitivity.tikz'], ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);


figure;
ind = find(Lia & Lid);
usolvers = unique(res(ind,:).solver);
warp_colors = [1:3 5:7];
for k = 1:numel(usolvers)
    hold on;
    keyboard;
    Lif = ismember(res.solver,usolvers(k));
    cdfplot(res(find(Lif),:).rewarp);
    hold off;
end



%ax5 = make_grouped_boxplot(res(ind,:), {'rewarp'},{ 'sigma', 'solver'}, ...
%                           'ylim', [0 40], ...
%                           'yticks',[0:10:50], ...
%                           'location','northwest', ...
%                           'colors', color_list(warp_colors,:), ...
%                           'ylabel', '$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels]');
%
%drawnow;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/rewarp_sensitivity.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%ax6 = make_grouped_boxplot(res(ind,:), {'ransac_rewarp'},{ 'sigma', 'solver'}, ...
%                           'ylim', [0 40], ...
%                           'yticks',[0:10:50], ...
%                           'location','northwest', ...
%                           'colors', color_list(warp_colors,:), ...
%                           'ylabel', '$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels]');
%drawnow;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/ransac_rewarp_sensitivity.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%

%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/lambda_stability.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);

%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/real_sols.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
