function [] = make_sensitivity_figs()
greedy_repeats_init('..');
%sensitivity = load('sensitivity_20180311.mat');
sensitivity = load('sensitivityrt.mat');
data = innerjoin(sensitivity.res,sensitivity.gt, ...
                 'LeftKeys','ex_num','RightKeys','ex_num');
q_gt = unique(data.q_gt)*sum(2*sum(sensitivity.cam.cc))^2;

assert(numel(q_gt)>0,'Cannot have different distortion parameters');
qres = array2table([data.q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    data.ransac_q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    1-data.q./data.q_gt ...
                    1-data.ransac_q./data.q_gt ...
                    data.rewarp ...
                    data.ransac_rewarp ], ...
                   'VariableNames', ...
                   {'q','ransac_q', 'q_relerr', ...
                    'ransac_q_relerr', 'rewarp','ransac_rewarp'}); 

res = [data(:,{'ex_num','scene_num','solver','sigma'}) qres];
solver_list = unique(res.solver);

%Lia = res.sigma == 1; 
Lia = res.sigma > 0;
Lib = ismember(res.solver, ...
               setdiff(solver_list, {'$\mH22\vl s$'}));
Libb = ismember(res.solver, ...
               setdiff(solver_list, {'$\mH22\vl$'}));
Lic = ismember(res.solver, ...
               setdiff(solver_list, '$\mH22\vl s$'));
Lid = ...
ismember(res.solver,setdiff(solver_list,{'$\mH22\lambda$'}));

color_list = [ 0 1 1; ...
               1 0 1; ...
               0 0 0; ...
               1 1 0; ...
               1 0.5490 0; ...
               0 0 1; ...
               0 1 0; ...
               1 0 0];

lbound = q_gt-4;
ubound = q_gt+4;

axis_options = {'enlargelimits=false'}  
lambda_colors = [5:8];

ind = find(Lia & Lib);
ind = find(Lia & Lib & Libb);
ax1 = make_grouped_boxplot(res(ind,:), ...
                           {'q'},{ 'sigma', 'solver' }, ...
                           'ylabel', 'Estimated distortion parameter $\hat{ \lambda }$', ...
                           'ylim', [lbound ubound], ...
                           'yticks',[lbound:2:ubound], ...
                           'truth', q_gt, ...
                           'location','northwest', ...
                           'colors', color_list(lambda_colors,:));

drawnow;
cleanfigure;
matlab2tikz('/home/prittjam/Documents/eccv18/fig/lambda_sensitivity_rt.tikz',...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax2 = make_grouped_boxplot(res(ind,:), ...
                           {'ransac_q'},{ 'sigma','solver' }, ...
                           'ylabel', 'Estimated distortion parameter $\hat{ \lambda }$', ...
                           'ylim', [lbound ubound], ...
                           'yticks',[lbound:2:ubound], ...
                           'truth', q_gt, ...
                           'location','northwest', ...
                           'colors', color_list(lambda_colors,:));
drawnow;
cleanfigure;
matlab2tikz('/home/prittjam/Documents/eccv18/fig/ransac_lambda_sensitivity_rt.tikz',...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax3 = make_grouped_boxplot(res(ind,:), {'q_relerr'},{ 'sigma', 'solver' }, ...
                           'ylim', [-0.6 0.6], ...
                           'yticks',[-0.8:0.2:0.8], ...
                           'truth', 0.0, ...
                           'location','northwest', ...
                           'colors', color_list(lambda_colors,:), ...
                            'ylabel', '$(\lambda-\hat{\lambda})/\lambda$');
drawnow;
cleanfigure;
matlab2tikz(['/home/prittjam/Documents/eccv18/fig/' ...
             'rel_lambda_sensitivity_rt.tikz'], ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax4 = make_grouped_boxplot(res(ind,:), {'ransac_q_relerr'},{ 'sigma', 'solver' }, ...
                           'ylim', [-0.6 0.6], ...
                           'yticks',[-0.8:0.2:0.8], ...
                           'truth', 0.0, ...
                           'location','northwest', ...
                           'colors', color_list(lambda_colors,:), ...
                           'ylabel', '$(\lambda-\hat{\lambda})/\lambda$');
drawnow;
cleanfigure;
matlab2tikz(['/home/prittjam/Documents/eccv18/fig/' ...
             'ransac_rel_lambda_sensitivity_rt.tikz'], ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

figure;
ind = find(Lia & Lid);
usolvers = unique(res(ind,:).solver);
warp_colors = [3:4 6:8];

%usolvers = usolvers([1 4 2 5 3 6]);
%warp_colors = warp_colors([1 4 2 5 3 6]);
%for k = 1:numel(usolvers)
%    hold on;
%    ind2 = ismember(res(ind,:).solver,usolvers(k));
%    h = cdfplot(res(ind(ind2),:).rewarp);
%    set(h,'color', ...
%          color_list(warp_colors(k),:));
%    hold off;
%end
%xlim([0 20]);
%xlabel('$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels] at $\sigma=1$ pixel', ...
%       'Interpreter','Latex','Color','k'); 
%ylabel('$p(x < \Delta^{\mathrm{warp}}_{\mathrm{RMS}})$', ...
%       'Interpreter','Latex');
%grid off;
%title('Empirical CDF of RMS warp error');
%legend('a','b','c','d','e','f','Location','northwest');
%drawnow;
%cleanfigure;
%matlab2tikz(['/home/prittjam/Documents/eccv18/fig/' ...
%             'ecdf_warp_1px.tikz'], ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
ax5 = make_grouped_boxplot(res(ind,:), {'rewarp'},{ 'sigma', 'solver'}, ...
                           'ylim', [0 40], ...
                           'yticks',[0:10:50], ...
                           'location','northwest', ...
                           'colors', color_list(warp_colors,:), ...
                           'ylabel', '$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels]');

drawnow;
cleanfigure;
matlab2tikz('/home/prittjam/Documents/eccv18/fig/rewarp_sensitivity_rt.tikz', ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax6 = make_grouped_boxplot(res(ind,:), {'ransac_rewarp'},{ 'sigma', 'solver'}, ...
                           'ylim', [0 40], ...
                           'yticks',[0:10:50], ...
                           'location','northwest', ...
                           'colors', color_list(warp_colors,:), ...
                           'ylabel', '$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels]');
drawnow;
cleanfigure;
matlab2tikz('/home/prittjam/Documents/eccv18/fig/ransac_rewarp_sensitivity_rt.tikz', ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

keyboard;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/lambda_stability.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%cleanfigure;
%axis_options = {'enlargelimits=false'} 
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/real_sols.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
