function m = scene_get_tc(dr1,dr2,cfg)
global conn

[keys,subtypes] = cvdb_make_dr_keys(cfg);

if (numel(subtypes) > 0)
    for i = 1:numel(keys)
        [m.(subtypes{i}),is_found] = cvdb_sel_tc(conn, ...
                                                 dr1.img_id, ...
                                                 dr2.img_id, ...
                                                 keys{i});
        if ~is_found
            m.(subtypes{i}) = scene_make_tc(dr1.(subtypes{i}), ...
                                            dr2.(subtypes{i}), ...
                                            cfg);
            cvdb_ins_tc(conn, ...
                        dr1.img_id, ...
                        dr2.img_id, ...
                        keys{i}, ...
                        m.(subtypes{i}));
        end
    end
else
    [m,is_found] = cvdb_sel_tc(conn,dr1.img_id,dr2.img_id,keys{1});
    if ~is_found
        m = scene_make_tc(dr1, ...
                          dr2, ...
                          cfg);
        cvdb_ins_tc(conn, ...
                    dr1.img_id, ...
                    dr2.img_id, ...
                    keys{1}, ...
                    m);
    end
end