function dr = scene_construct_dr(geom,sift,cls,gid,subgenid, ...
                                 detector,descriptor,img_id)
if nargin < 1
    dr = struct('geom',{}, ...
                'u',{}, ...
                'sifts',{}, ...
                'xsifts',{}, ...
                'id',{}, ...
                'gid',{}, ...
                's',{}, ...
                'num_dr',0, ...
                'name',{}, ... 
                'genid',{}, ...
                'img_id',{}, ...
                'class',{});
else
    dr = struct;

    [scls,ind] = sort(reshape(cls,1,[]),'ascend');

    dr.geom = geom(:,ind);
    dr.u = laf_get_3p_from_A(laf_unwrap_A(dr.geom));
    dr.sifts = sift(:,ind);
    dr.xsifts = descriptor.normalize(dr.sifts);
    dr.id = [1:size(dr.geom,2)];
    dr.gid = [gid:gid+size(dr.geom,2)-1];
    dr.s = true(1,size(dr.geom,2));
    dr.num_dr = size(dr.geom,2);
    dr.name = detector.name;
    dr.genid = drname2id(dr.name);
    dr.img_id = img_id;
    dr.class = scls;
end



