%
%  Copyright (c) 2018 James Pritts
%  Licensed under the MIT License (see LICENSE for details)
%
%  Written by James Pritts
%
function affpt = laf_3p_to_affpt(u,ids)
if nargin < 2
    ids = 1:size(u,2);
end

A = reshape(cell2mat(laf_3p_to_A(u)'),3,3,[]);
affpt = struct('x',num2cell(squeeze(A(1,3,:))'), ...
               'y',num2cell(squeeze(A(2,3,:))'), ...
               'a11',num2cell(squeeze(A(1,1,:))'), ...
               'a12',num2cell(squeeze(A(1,2,:))'), ...
               'a21',num2cell(squeeze(A(2,1,:))'), ...
               'a22',num2cell(squeeze(A(2,2,:))'), ...
               'id',num2cell(ids));