function [] = make_cdf_warp_fig()
repeats_init();
axis_options = {'enlargelimits=false'};  
sensitivity = load('ct_sensitivity_20180623.mat');

data = innerjoin(sensitivity.res,sensitivity.gt, ...
                 'LeftKeys','ex_num','RightKeys','ex_num');
q_gt = unique(data.q_gt)*sum(2*sum(sensitivity.cam.cc))^2;

assert(numel(q_gt)>0,'Cannot have different distortion parameters');
qres = array2table([data.q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    data.ransac_q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    1-data.q./data.q_gt ...
                    1-data.ransac_q./data.q_gt ...
                    data.rewarp ...
                    data.ransac_rewarp ], ...
                   'VariableNames', ...
                   {'q','ransac_q', 'q_relerr', ...
                    'ransac_q_relerr', 'rewarp','ransac_rewarp'}); 

res = [data(:,{'ex_num','scene_num','solver','sigma'}) qres];
solver_list = unique(res.solver,'stable');

Lia = res.sigma == 1;
Lid = ismember(res.solver,setdiff(solver_list,{'$\mH22\lambda$'}));

solver_ind = find(Lid(1:numel(solver_list)));

is_valid = Lia & Lid;

color_list = [ 0 1 1; ...
               1 0 1; ...
               1 0.5490 0; ...
               1 1 0; ...
               0 0 0; ...
               0 0 1; ...
               0 1 0; ...
               1 0 0];

color_list = color_list(solver_ind,:);

ind = find(is_valid);
for k = 1:numel(solver_ind)
    ind2 = find(ismember(res.solver(ind),solver_list(solver_ind(k))));
    hold on;
    h = cdfplot(res.rewarp(ind(ind2)));
    set(h,'color',color_list(k,:));
    hold off;
end

xlim([0 20]);
xlabel('$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels] at $\sigma=1$ pixel', ...
       'Interpreter','Latex','Color','k'); 
ylabel('$p(x < \Delta^{\mathrm{warp}}_{\mathrm{RMS}})$', ...
       'Interpreter','Latex');
grid off;
title('Empirical CDF of RMS warp error');
legend('a','b','c','d','e','f','Location','northwest');
drawnow;

keyboard;
cleanfigure('targetResolution',100);
%matlab2tikz(['/home/jbpritts/Documents/eccv18/fig/' ...
%             'ecdf_warp_1px_ct.tikz'], ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
