 axis_options = {'enlargelimits=false'}  
tmp1 = load('sensitivity_20180311.mat');
res1 = tmp1.res;
tmp2 = load('sensitivity_to_merge.mat');
res2 = tmp2.res;
data1 = innerjoin(res1,tmp1.gt, ...
                 'LeftKeys','ex_num','RightKeys','ex_num');
data2 = innerjoin(res2,tmp2.gt,...
                  'LeftKeys','ex_num','RightKeys','ex_num');
solver_list = unique(res1.solver);
Lia = ismember(res1.solver, ...
               setdiff(solver_list, ...
                       {'$\mH22\vl s$'}));
data1 = data1(Lia,:);

tmp1 = string(data1.solver);
tmp2 = string(data2.solver);
newres1 = categorical([string(data1.solver); ...
           string(data2.solver)]);            
data = [data1(:,{'sigma','rewarp','ransac_rewarp'}); ...
        data2(:,{'sigma','rewarp','ransac_rewarp'})];

res = [array2table(newres1,'VariableNames',{'solver'}) ...
       array2table([data.sigma data.rewarp data.ransac_rewarp], ...
       'VariableNames', {'sigma','rewarp','ransac_rewarp'})];

solver_list = unique(res.solver);
Lia = res.sigma == 1; 
%Lia = res.sigma > 0; 
Lid = ismember(res.solver,setdiff(solver_list,{'$\mH22\lambda$'}));
color_list = [ 0 1 1; ...
               1 0 1; ...
               0 0 0; ...
               1 1 0; ...
               0 0 1; ...
               0 1 0; ...
               1 0 0];

figure;
ind = find(Lia & Lid);
usolvers = unique(res(ind,:).solver);
usolvers = usolvers([ 5 1 4 6 2 7 3 ]);

for k = 1:numel(usolvers)
    hold on;
    ind2 = ismember(res(ind,:).solver,usolvers(k));
    h = cdfplot(res(ind(ind2),:).rewarp);
    set(h,'color', ...
          color_list(k,:));
    hold off;
end
xlim([0 20]);
xlabel('$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels] at $\sigma=1$ pixel', ...
       'Interpreter','Latex','Color','k'); 
ylabel('$p(x < \Delta^{\mathrm{warp}}_{\mathrm{RMS}})$', ...
       'Interpreter','Latex');
grid off;
title('Empirical CDF of RMS warp error');
legend('a','b','c','d','e','f','Location','northwest');
drawnow;
cleanfigure;

matlab2tikz(['/home/prittjam/Documents/eccv18/fig/' ...
             'ecdf_warp_1px.tikz'], ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

%ax5 = make_grouped_boxplot(res(ind,:), {'rewarp'},{ 'sigma', 'solver'}, ...
%                           'ylim', [0 40], ...
%                           'yticks',[0:10:50], ...
%                           'location','northwest', ...
%                           'colors', color_list(warp_colors,:), ...
%                           'ylabel', '$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels]');
%
%drawnow;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/rewarp_sensitivity.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%ax6 = make_grouped_boxplot(res(ind,:), {'ransac_rewarp'},{ 'sigma', 'solver'}, ...
%                           'ylim', [0 40], ...
%                           'yticks',[0:10:50], ...
%                           'location','northwest', ...
%                           'colors', color_list(warp_colors,:), ...
%                           'ylabel', '$\Delta^{\mathrm{warp}}_{\mathrm{RMS}}$ [pixels]');
%drawnow;
%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/ransac_rewarp_sensitivity.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%

%cleanfigure;
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/lambda_stability.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
%cleanfigure;
%axis_options = {'enlargelimits=false'} 
%matlab2tikz('/home/prittjam/Documents/eccv18/fig/real_sols.tikz', ...
%            'width', '\fwidth', ...
%            'extraAxisOptions',axis_options);
%
