function [] = make_sensitivity_figs()
repeats_init();
sensitivity = load('rt_sensitivity_20190302.mat');

data = innerjoin(sensitivity.res,sensitivity.gt, ...
                 'LeftKeys','ex_num','RightKeys','ex_num');
q_gt = unique(data.q_gt)*sum(2*sum(sensitivity.cam.cc))^2;

assert(numel(q_gt)>0,'Cannot have different distortion parameters');
qres = array2table([data.q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    data.ransac_q*sum(2*sum(sensitivity.cam.cc))^2 ...
                    1-data.q./data.q_gt ...
                    1-data.ransac_q./data.q_gt ...
                    data.rewarp ...
                    data.ransac_rewarp ], ...
                   'VariableNames', ...
                   {'q','ransac_q', 'q_relerr', ...
                    'ransac_q_relerr', 'rewarp','ransac_rewarp'}); 

res = [data(:,{'ex_num','scene_num','solver','sigma'}) qres];
solver_list = unique(res.solver);

Lia = res.sigma > 0;
Lib = ismember(res.solver, ...
               setdiff(solver_list, {'$\mH22\vl s$','$\mH22\vl$'}));
Lid = ismember(res.solver,setdiff(solver_list,{'$\mH22\lambda$'}));

color_list = [ 0 1 1; ...
               1 0 1; ...
               1 0.5490 0; ...
               1 1 0; ...
               0 0 0; ...
               0 0 1; ...
               0 1 0; ...
               1 0 0];

lbound = q_gt-4;
ubound = q_gt+4;

axis_options = {'enlargelimits=false'};  

is_valid = Lia & Lib;

ax1 = make_grouped_boxplot(res(is_valid,:), ...
                           {'q'},{ 'sigma', 'solver' }, ...
                           'ylabel', 'Estimated distortion parameter $\hat{ \lambda }$', ...
                           'ylim', [lbound ubound], ...
                           'yticks',[lbound:2:ubound], ...
                           'truth', q_gt, ...
                           'location','northwest', ...
                           'colors', color_list(is_valid(1:size(color_list,1)),:));

drawnow;
cleanfigure;
matlab2tikz('/home/jbpritts/Documents/eccv18/fig/lambda_sensitivity_ct.tikz',...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax2 = make_grouped_boxplot(res(is_valid,:), ...
                           {'ransac_q'},{ 'sigma','solver' }, ...
                           'ylabel', 'Estimated distortion parameter $\hat{ \lambda }$', ...
                           'ylim', [lbound ubound], ...
                           'yticks',[lbound:2:ubound], ...
                           'truth', q_gt, ...
                           'location','northwest', ...
                           'colors', color_list(is_valid(1:size(color_list,1)),:));
drawnow;
cleanfigure;
matlab2tikz('/home/jbpritts/Documents/eccv18/fig/ransac_lambda_sensitivity_ct.tikz',...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax3 = make_grouped_boxplot(res(is_valid,:), {'q_relerr'},{ 'sigma', 'solver' }, ...
                           'ylabel', '$(\lambda-\hat{\lambda})/\lambda$', ...
                           'ylim', [-0.6 0.6], ...
                           'yticks',[-0.8:0.2:0.8], ...
                           'truth', 0.0, ...
                           'location','northwest', ...
                           'colors',  color_list(is_valid(1: ...
                                                  size(color_list,1)),:), ...
                           'legend','off');
drawnow;
cleanfigure;
matlab2tikz(['/home/jbpritts/Documents/eccv18/fig/' ...
             'rel_lambda_sensitivity_ct.tikz'], ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax4 = make_grouped_boxplot(res(is_valid,:), {'ransac_q_relerr'},{ 'sigma', 'solver' }, ...
                           'ylabel', '$(\lambda-\hat{\lambda})/\lambda$', ...
                           'ylim', [-0.6 0.6], ...
                           'yticks',[-0.8:0.2:0.8], ...
                           'truth', 0.0, ...
                           'location','northwest', ...
                           'colors',  color_list(is_valid(1:size(color_list,1)),:));
drawnow;
cleanfigure;
matlab2tikz(['/home/jbpritts/Documents/eccv18/fig/' ...
             'ransac_rel_lambda_sensitivity_ct.tikz'], ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

is_valid = Lia & Lid;

ax5 = make_grouped_boxplot(res(is_valid,:), {'rewarp'},{ 'sigma', 'solver'}, ...
                           'ylabel', ['$\Delta^{\mathrm{warp}}_{\' ...
                    'mathrm{RMS}}$ [pixels]'], ...
                           'ylim', [0 40], ...
                           'yticks',[0:10:50], ...
                           'location','northwest', ...
                           'colors', color_list(is_valid(1:size(color_list,1)),:));


drawnow;
cleanfigure;
matlab2tikz('/home/jbpritts/Documents/eccv18/fig/rewarp_sensitivity_ct.tikz', ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);

ax6 = make_grouped_boxplot(res(is_valid,:), {'ransac_rewarp'},{ 'sigma', 'solver'}, ...
                           'ylabel', ['$\Delta^{\mathrm{warp}}_{\' ...
                    'mathrm{RMS}}$ [pixels]'], ...
                           'ylim', [0 40], ...
                           'yticks',[0:10:50], ...
                           'location','northwest', ...
                           'colors', color_list(is_valid(1:size(color_list,1)),:),'legend','off');
drawnow;

keyboard;
cleanfigure;
matlab2tikz('/home/jbpritts/Documents/eccv18/fig/ransac_rewarp_sensitivity_ct.tikz', ...
            'width', '\fwidth', ...
            'extraAxisOptions',axis_options);